version: "3.8"

services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    container_name: frontend-app
    ports:
      - "80:5000"
    environment:
      - BACKEND_URL=http://10.0.138.63:8080
    restart: unless-stopped